#!/bin/bash

# Stores the directory where the script was called from
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ "$1" = -h ] || [ "$1" = --help ]; then
    "$DIR"/master_blaster.sh -h
else
    "$DIR"/master_blaster.sh $@
fi


