#!/bin/bash

# make sure MASTER_BLASTER_PATH is defined
# or non-empty
if [[ -z "$MASTER_BLASTER_PATH" ]]; then
    echo MASTER_BLASTER_PATH must be defined, please refer to
    echo the 'install.sh' script.

    exit 1
fi    

sbatch "$MASTER_BLASTER_PATH"/master_blaster.sh $@
